################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# python
  - numpy=2.4.2
  - python=3.12.12

# modern jupyter interface
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - ipykernel

# # jupyter
#   - jupyter=1.0.0
#   - jupyterlab=3.5.0
#   - notebook=6.4.12

# computing stuff
  - tensorly=0.9.0
  - torch=2.5.1

# plotting stuff
  - matplotlib=3.10.8
