################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
  # python
  - python=3.10.15
  - numpy=1.24.0
  - matplotlib=3.9.2
  - scipy=1.14.1
  - pandas==2.2.3

  # modern jupyter interface
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - ipykernel
  - nb_conda_kernels

  # computing stuff
  - fenics=2019.1.0
  - meshio=5.3.5
  - gmsh=4.13.1
  - libglu
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - xorg-libxrender
  - xorg-libxxf86vm

  # pip for additional packages
  - pip=24.2
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch==2.12.0
    - torchvision==0.27.0
    - dolfin_mech==2026.5.7
    - tensorly==0.9.0