name: pot

channels:
  - conda-forge

dependencies:
  # python
  - python=3.13.2
  - ipykernel
  - scipy=1.15.2

  # computing stuff
  - meshio=5.3.5
  - pyvista==0.44.1
  - scikit-learn==1.6.1

  # pip for additional packages
  - pip=25.1
  - pip:
    - POT==0.9.5